language: node_js

node_js:
  - 8
  - 6

script:
  - npm run lint 
  - npm run test::ci
  - npm run build

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release